ParentingForLifelongHealth/plh-kids-app-tz-content

app_data/sheets/global/navigation_global.json, app_data/sheets/template/home_screen.json, config.ts
- Content sync
- Update config to accommodate translations
=> content: 1.1.3

app_data/sheets/generator/check_in_article_generator.json, app_data/sheets/template/generated/article_check_in_1.json, app_data/sheets/template/generated/article_check_in_10.json, app_data/sheets/template/generated/article_check_in_11.json, app_data/sheets/template/generated/article_check_in_12.json, app_data/sheets/template/generated/article_check_in_13.json, app_data/sheets/template/generated/article_check_in_14.json, app_data/sheets/template/generated/article_check_in_15.json, app_data/sheets/template/generated/article_check_in_16.json, app_data/sheets/template/generated/article_check_in_2.json, app_data/sheets/template/generated/article_check_in_3.json, app_data/sheets/template/generated/article_check_in_4.json, app_data/sheets/template/generated/article_check_in_5.json, app_data/sheets/template/generated/article_check_in_6.json, app_data/sheets/template/generated/article_check_in_7.json, app_data/sheets/template/generated/article_check_in_8.json, app_data/sheets/template/generated/article_check_in_9.json, config.ts
Amend grid width in check-in articles
Before: 
After:
=> content: 1.1.15

app_data/assets/contents.json, app_data/sheets/template/relax.json, app_data/translations_source/translated_strings/translated.tz_sw.json, config.ts
- Add swahili version of join_child video
- debug relax nav buttons
=> content: 1.1.21

config.ts
PR to update code version to include drop shadow on radio button grid
=> content: 1.1.25

app_data/sheets/data_list/check_in.json, app_data/sheets/data_list/connect_articles.json, app_data/translations/tz_sw/strings.json, app_data/translations_source/translated_strings/translated.tz_sw.json, config.ts
- add texts to emojis as requested by Orli
=> content: 1.1.26

config.ts, reports/summary.json, reports/summary.md
=> content: 1.1.66

app_data/sheets/contents.json, app_data/sheets/data_list/characters.json, app_data/sheets/data_list/generated/modules_released.json, app_data/sheets/data_list/modules.json, app_data/sheets/template/article.json, app_data/sheets/template/relax.json, config.ts
=> content: 1.1.74

config.ts
Update android assets. Closes #97
=> content: 1.1.84

app_data/assets/contents.json, app_data/assets/images/icons/chevron_back_white.svg, app_data/assets/images/icons/chevron_forward_white.svg, app_data/sheets/contents.json, app_data/sheets/template/book_button.json, app_data/sheets/template/lib_books.json, app_data/sheets/template/nav_buttons.json, config.ts, reports/summary.json, reports/summary.md
- Remove filters and favourites from library (relates to #93)
- Unsuccesful attempt to refactor nav_buttons to include icons (relates to #100)
=> content: 1.1.86

config.ts
update config to 
- include custom favicon
- no longer collapse header
=> content: 1.1.96

app_data/sheets/template/book_cover.json, app_data/sheets/template/book_page.json, config.ts
- enable navigating back on first book page
- enable closing book on last book page
=> content: 1.1.97

app_data/sheets/data_list/generated/connect_books_connect_article_tasks.json, app_data/sheets/data_list/generated/connect_check_in_article_tasks.json, app_data/sheets/data_list/generated/connect_how_connect_article_tasks.json, app_data/sheets/data_list/generated/connect_power_connect_article_tasks.json, app_data/sheets/data_list/generated/connect_relax_article_tasks.json, app_data/sheets/data_list/generated/connect_why_connect_article_tasks.json, app_data/sheets/data_list/generated/join_caring_child_article_tasks.json, app_data/sheets/data_list/generated/join_caring_you_article_tasks.json, app_data/sheets/data_list/generated/join_check_in_article_tasks.json, app_data/sheets/data_list/generated/join_get_started_article_tasks.json, app_data/sheets/data_list/generated/join_learn_books_article_tasks.json, app_data/sheets/data_list/generated/join_relax_article_tasks.json, app_data/sheets/data_list/generated/join_welcome_article_tasks.json, app_data/sheets/template/activity_carousel.json, app_data/sheets/template/book_button.json, app_data/sheets/template/book_cover.json, app_data/sheets/template/book_image_landscape.json, app_data/sheets/template/book_landing.json, app_data/sheets/template/home_practice_options.json, app_data/sheets/template/module_landing.json, config.ts
- Fix bug where previous book was shown (now first set field then pop up book)
- Set max image height of book images to 400px to fit better on a landscape page
- Add access timestamps to home practice and resource centre buttons (closes #103) - this should in future be done with dynamic data
- Remove unpopulated progress bar because it was throwing errors
=> content: 1.1.107

app_data/sheets/template/article.json, config.ts, reports/summary.json, reports/summary.md
Show default language youtube video when other language youtube video link is missing
=> content: 1.2.4

app_data/sheets/contents.json, app_data/sheets/template/app_launch_calculations.json, app_data/sheets/template/language_select.json, config.ts, reports/summary.json, reports/summary.md
Some changes to the library app menu sheets: 
- add first launch version and timestamp 
- store timestamp of every launch (closes one item in #139)
- add force restart when changing language
=> content: 1.2.5

app_data/sheets/data_list/connect_articles.json, app_data/sheets/data_list/generated/connect_article_tasks.json, app_data/sheets/data_list/generated/join_article_tasks.json, app_data/sheets/data_list/join_articles.json, config.ts
update youtube links to long version
=> content: 1.2.9

app_data/sheets/contents.json, app_data/sheets/data_list/characters.json, app_data/sheets/data_list/generated/connect_article_tasks.json, app_data/sheets/data_list/generated/create_article_tasks.json, app_data/sheets/data_list/generated/join_article_tasks.json, app_data/sheets/data_list/generated/module_tasks.json, app_data/sheets/data_list/generated/play_article_tasks.json, app_data/sheets/data_list/lifecycle_actions/launch_actions.json, app_data/sheets/data_list/play_articles.json, app_data/sheets/data_list/user_gender.json, app_data/sheets/data_list/user_type.json, app_data/sheets/global/user_data_global.json, app_data/sheets/template/module.json, app_data/sheets/template/module_card.json, app_data/sheets/template/module_path.json, app_data/sheets/template/user_data.json, config.ts, reports/summary.json, reports/summary.md
=> content: 1.2.12

config.ts
Update default app language to Swahili
=> content: 1.2.15

config.ts
To avoid accidentally releasing 1.2.16
=> Update content version to 1.2.17

app_data/sheets/template/home_screen.json, app_data/sheets/template/nav_buttons.json, config.ts
Add padding to homescreen header
Before / After:
=> content: 1.2.21

app_data/sheets/template/activities.json, config.ts
=> content: 1.2.28

app_data/assets/contents.json, app_data/sheets/contents.json, app_data/sheets/template/book_cover.json, app_data/sheets/template/book_landing.json, app_data/sheets/template/footer.json, app_data/sheets/template/module_path.json, app_data/sheets/template/resource_centre.json, app_data/sheets/template/settings.json, app_data/sheets/template/support_activities.json, app_data/sheets/tour/home_screen_tour.json, config.ts, reports/summary.json, reports/summary.md
1. I’ve added additional timestamps for the following sections:
- Books – Read with Child and Start Reading buttons
- Songs 
- Additional Resources
- Support Information
- Resource Centre buttons
2. A home tour so the team can review it and decide whether it's still usable, even with the current bugs.
=> content: 1.3.9
